using Autodesk.Revit.DB;
using Autodesk.Revit.DB.Visual;
using Autodesk.Revit.UI;
using Autodesk.Revit.UI.Selection;
using CommunityToolkit.Mvvm.DependencyInjection;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using TurUpAILinesegmentation;

namespace TurUpAIExportSurfaceToFemix
{
    public partial class ClassExportToFemix
    {
        private UIDocument uidoc;
        public ClassExportToFemix(UIDocument _uidoc)
        {
            uidoc = _uidoc;
        }

        //private void generateMesh()
        //{
        //    string tempPath = Path.GetTempPath();
        //    MessageBox.Show("Temporary Directory: " + tempPath);

        //    TurUpAIRunGmsh.ClassMeshGeneration classMeshGeneration = new TurUpAIRunGmsh.ClassMeshGeneration();
        //    classMeshGeneration.generateMesh(".geo");
        //}
        public void exportSelectedFaces()
        {
            TurUpAIRunGmsh.ClassMeshGeneration meshgenerator = new TurUpAIRunGmsh.ClassMeshGeneration();

            using (Transaction tx = new Transaction(uidoc.Document, "clear selection"))
            {
                tx.Start();
                uidoc.Selection.SetElementIds(new List<ElementId>());
                uidoc.RefreshActiveView();
                tx.Commit();
            }

            IList<Reference> references = uidoc.Selection.PickObjects(ObjectType.Face, "Select faces to export to Femix");
            
            StringBuilder GmshGeoFile = new StringBuilder("//## Generated by Kamyar_ba@yahoo.com \r\n");


            int curveCounter = 1;
            foreach (Reference reference in references) 
            {
                ElementId motherElementId = reference.ElementId;
                GeometryObject geometryObject = uidoc.Document.GetElement(reference).GetGeometryObjectFromReference(reference);
                Face face = geometryObject as Face;
                String area = face.Area.ToMeters().ToString("0.00");
                //TaskDialog.Show ("element id", $"{elementId.ToString()}");
                //String fileName = $"e{elementId}f{geometryObject.Id}";
                
                List<Edge> curvesOfFace = new List<Edge>();
                foreach (EdgeArray edgeArray in face.EdgeLoops)
                {
                    foreach (Edge edge in edgeArray)
                    {
                        curvesOfFace.Add(edge);
                    }                    
                }

                StringBuilder GmshFacegeometry = createSurfaceGmshGeometry(curvesOfFace, area, motherElementId, geometryObject.Id, curveCounter);
                GmshGeoFile.AppendLine(GmshFacegeometry.ToString());
                curveCounter += curvesOfFace.Count();
            }


            StringBuilder gmshMeshSeting = GmshMeshSeting();
            GmshGeoFile.AppendLine(gmshMeshSeting.ToString());

            string geofilePath = Path.GetDirectoryName(uidoc.Document.PathName) + "\\Geometry.geo";
            string meshDirPath = Path.GetDirectoryName(uidoc.Document.PathName);

            //if (File.Exists(geofilePath))
            //    File.Delete(geofilePath);
            //if (File.Exists(meshDirPath + "\\output_mesh.msh"))
            //    File.Delete(meshDirPath + "\\output_mesh.msh");

            try
            {
                using (StreamWriter writer = new StreamWriter(geofilePath))
                {
                    writer.Write(GmshGeoFile.ToString());
                }
            }
            finally
            {
                //meshgenerator.generateMesh(geofilePath);
                meshgenerator.run_GMSH_exe(geofilePath);
                //TaskDialog.Show("Info", $"Geometry is created");
            }

            GmshToFemix.ClassGMSHConvert gMSHConvertFemix = new GmshToFemix.ClassGMSHConvert();

            

            var (GROUP_NAMES, POINT_COORDINATES, ELEMENT_NODES, ELEMENT_PROPERTIES) =
                gMSHConvertFemix.ConvertMSHtoFemixmesh(meshDirPath+ "\\output_mesh.msh", null);

            string femixdatafile = $"{Path.GetDirectoryName(uidoc.Document.PathName)}\\femix_gl.dat";
            
            //if (File.Exists(femixdatafile))
            //    File.Delete(femixdatafile);

            using (StreamWriter writer = new StreamWriter(femixdatafile))
            {
                writer.WriteLine($"{GROUP_NAMES}\n\n{POINT_COORDINATES}\n\n{ELEMENT_NODES}\n\n{ELEMENT_PROPERTIES}");
            }
            TaskDialog.Show("Info", $"The selected items exported to:\r\n{femixdatafile}");

        }

        private StringBuilder GmshMeshSeting()
        {
            StringBuilder GmshMeshSeting = new StringBuilder();
            GmshMeshSeting.AppendLine("//+");
            GmshMeshSeting.AppendLine("Recombine Surface{:};"); // Quadratic
            //stringBuilder.AppendLine("Recombine Volume{:};");
            GmshMeshSeting.AppendLine("Transfinite Surface{:};"); // Structured
            //stringBuilder.AppendLine("Transfinite Volume{:};");
            GmshMeshSeting.AppendLine("Geometry.Tolerance = 1e-3;");
            //Mesh.CharacteristicLengthMax = 0.1; // Set maximum mesh size
            //Mesh.CharacteristicLengthMin = 0.01; // Set minimum mesh size
            //Mesh.Algorithm = 5; // Set the meshing algorithm (e.g., Delaunay)
            //Mesh.RecombineAll = 1; // Recombine triangles into quads
            // Automatically generate the mesh when the file is opened
            //Mesh 2; // This command triggers the 2D mesh generation
            GmshMeshSeting.AppendLine("Mesh 2;");
            GmshMeshSeting.AppendLine("Coherence Mesh;"); // Remove all duplicate mesh nodes in the current mesh.


           GmshMeshSeting.AppendLine("Save \"output_mesh.msh\";");// Save the mesh in MSH format

           // GmshMeshSeting.AppendLine ("Save \"output_mesh.vtk\";");// Save the mesh in VTK format
            //gmsh - o your_script.geo

            return GmshMeshSeting;
        }

           private Dictionary<int, string> tempCurveCoordinates = new Dictionary<int, string>();
        public int? GettempCurveCoordinatesKeyByValue(string value)
        {
            // Check if the value exists in the dictionary
            if (tempCurveCoordinates.ContainsValue(value))
            {
                // Loop through the dictionary to find the key
                foreach (var pair in tempCurveCoordinates)
                {
                    if (pair.Value == value)
                    {
                        return pair.Key; // Return the key if the value matches
                    }
                }
            }
            return null; // Return null if the value does not exist
        }

        private StringBuilder createSurfaceGmshGeometry(List<Edge> edgesOfFace,string surfaceArea, ElementId solidElementId, int faceId, int curveCounter)
        {
            StringBuilder geometryStringBuilder = new StringBuilder($"//######## New Surface [Area={surfaceArea}]########\r\n");
            //stringBuilder.AppendLine("SetFactory(\"OpenCASCADE\");"); 
            string groupName = $"e{solidElementId}f{faceId}";
            string prescrobedMeshSize = TurUpAIexportSetting.parameters.Meshsize;
            geometryStringBuilder.AppendLine($"lc = {prescrobedMeshSize};\n");
            geometryStringBuilder.AppendLine($"Physical Surface(\"{groupName}\") = {{ }};\n");
           
            List<String> curveloop = new List<string>();
            XYZ previousStart = null;
            XYZ previousEnd = null;

            //TaskDialog.Show("all", string.Join("\n", TurUpAILinesegmentation.segments.edgeElementNumber.Select(kvp => $"{kvp.Key}: {kvp.Value}")));

            foreach (Edge edge in edgesOfFace)
            {
                
                Curve curve = edge.AsCurve();// It can be an Arc, Line, or HermiteSpline.
                
                string uniqCurveID = $"e{solidElementId}c{edge.Id}";


                String typeName = curve.GetType().Name;
                XYZ startpoint = curve.GetEndPoint(0);
                XYZ endpoint = curve.GetEndPoint(1);
                Double length = curve.Length;
                String curveLoopSign = "";

                // `newp', automatically selects a new point tag.
                // the special variables `newl', `newll, `news', `newsl' and `newv'
                // select new curve, curve loop, surface, surface loop and volume tags.
                int? curveKey = null;
                string curveValue = "";

                if (curve is Line line)
                {
                    geometryStringBuilder.AppendLine($"//  Revit line //");

                    geometryStringBuilder.AppendLine($"pStart = newp;");
                    geometryStringBuilder.AppendLine($"Point(pStart) = {{{startpoint.X.ToString("0.0")}, {startpoint.Y.ToString("0.0")}, {startpoint.Z.ToString("0.0")}, lc}};");
                    geometryStringBuilder.AppendLine($"pend = newp;");
                    geometryStringBuilder.AppendLine($"Point(pend) = {{{endpoint.X.ToString("0.0")}, {endpoint.Y.ToString("0.0")}, {endpoint.Z.ToString("0.0")}, lc}};");
                    geometryStringBuilder.AppendLine($"// line length = {length.ToString("0.0")} mm");
                    
                    curveValue = $"line{startpoint}{endpoint}";
                    curveKey = GettempCurveCoordinatesKeyByValue(curveValue);
                    if (curveKey != null)
                    {
                        geometryStringBuilder.AppendLine($"curve[{curveCounter}] = curve[{curveKey}];");
                    }
                    else
                    {
                        tempCurveCoordinates.Add(curveCounter, curveValue);
                        geometryStringBuilder.AppendLine($"curve[{curveCounter}] = newc;");
                        geometryStringBuilder.AppendLine($"Line(curve[{curveCounter}]) = {{pStart,pend}};");
                    }
                    geometryStringBuilder.AppendLine();

                    ++curveCounter;
                }
                else if (curve is Arc arc)
                {
                    XYZ center = arc.Center;
                    XYZ normal = arc.Normal;

                    geometryStringBuilder.AppendLine($"//  Revit arc  //");
                    geometryStringBuilder.AppendLine($"pStart = newp;");
                    geometryStringBuilder.AppendLine($"Point(pStart) = {{{startpoint.X.ToString("0.0")}, {startpoint.Y.ToString("0.0")}, {startpoint.Z.ToString("0.0")}, lc}};");
                    geometryStringBuilder.AppendLine($"pend = newp;");
                    geometryStringBuilder.AppendLine($"Point(pend) = {{{endpoint.X.ToString("0.0")}, {endpoint.Y.ToString("0.0")}, {endpoint.Z.ToString("0.0")}, lc}};");
                    geometryStringBuilder.AppendLine($"pcenter = newp;");
                    geometryStringBuilder.AppendLine($"Point(pcenter) = {{{center.X.ToString("0.0")}, {center.Y.ToString("0.0")}, {center.Z.ToString("0.0")}, lc}};");

                    geometryStringBuilder.AppendLine($"// Arc length = {length.ToString("0.0")} mm");

                    curveValue = $"arc{startpoint}{endpoint}{center}";
                    curveKey = GettempCurveCoordinatesKeyByValue(curveValue);
                    if (curveKey != null)
                    {
                        geometryStringBuilder.AppendLine($"curve[{curveCounter}] = curve[{curveKey}];");
                    }
                    else
                    {
                        tempCurveCoordinates.Add(curveCounter, curveValue);
                        geometryStringBuilder.AppendLine($"curve[{curveCounter}] = newc;");
                        geometryStringBuilder.AppendLine($"Circle(curve[{curveCounter}]) = {{pStart, pcenter, pend}};");
                    }

                    //Ellipse(3) = {st, cen, end, end};
                    geometryStringBuilder.AppendLine();


                    //TaskDialog.Show("h", center.ToString());


                    ++curveCounter;
                }
                else if (curve is HermiteSpline hermiteSpline)
                {
                    //p6 = newp;
                    //Point(p6 + 1) = { -61283.32024425951, -114891.1290102597, 0};
                    //IList<XYZ> tangents = hermiteSpline.Tangents;
                    IList<XYZ> controlPoints = hermiteSpline.ControlPoints;
                    geometryStringBuilder.AppendLine($"//  Revit hermite-Spline  //");

                    List<String> splinestring = new List<string>();
                    geometryStringBuilder.AppendLine($"pSp = newp;");
                    int numPoints = 10;
                    for (int i = 0; i <= numPoints; i++)
                    {
                        double t = (double)i / numPoints; // Parameter from 0 to 1
                        XYZ point = hermiteSpline.Evaluate(t, true); // Evaluate the spline at t //true: evenly spaced points [0-1]
                        geometryStringBuilder.AppendLine($"Point(pSp + {i + 1}) = {{{point.X.ToString("0.0")}, {point.Y.ToString("0.0")}, {point.Z.ToString("0.0")}, lc}};");
                        splinestring.Add($"pSp + {i + 1}");
                    }

                    geometryStringBuilder.AppendLine($"// Spline length = {length.ToString("0.0")} mm");
                    
                    
                    curveValue = $"spline{startpoint}{endpoint}";
                    curveKey = GettempCurveCoordinatesKeyByValue(curveValue);
                    if (curveKey != null)
                    {
                        geometryStringBuilder.AppendLine($"curve[{curveCounter}] = curve[{curveKey}];");
                    }
                    else
                    {
                        tempCurveCoordinates.Add(curveCounter, curveValue);
                        geometryStringBuilder.AppendLine($"curve[{curveCounter}] = newc;");
                        geometryStringBuilder.AppendLine($"Spline(curve[{curveCounter}]) = {{{String.Join(", ", splinestring)}}};");
                    }


                    geometryStringBuilder.AppendLine();
                    ++curveCounter;
                }

                // Transfinite
                if (segments.edgeElementNumber.ContainsKey(uniqCurveID))
                {
                    var Transfiniteitems = TurUpAILinesegmentation.ClassSegmentation.GetCustomId(uniqCurveID);
                    int nPoints = Transfiniteitems.Item1;
                    double vProgress = Transfiniteitems.Item2;

                    string progressSign ="";
                    if (vProgress < 0)
                    {
                        progressSign = "-";
                        vProgress = Math.Abs(vProgress); 
                    }

                    if (nPoints > 1) {
                        geometryStringBuilder.AppendLine($"Transfinite Curve {{{progressSign}curve[{curveCounter-1}]}} = {nPoints} Using Progression {vProgress};");
                    }
                }


                if (previousEnd != null)
                {
                    // The coordinates of the curves must be in a sequence
                    if (areCoordinatesEqual(startpoint, previousEnd) == true)
                    {
                        curveLoopSign = "";
                        previousStart = startpoint;
                        previousEnd = endpoint;

                    }
                    else if (areCoordinatesEqual(startpoint, previousStart) == true)
                    {
                        // remove last curve in a surface and change its sign becuase its direction is not correct
                        curveloop.RemoveAt(curveloop.Count - 1);
                        // Change its direction
                        curveloop.Add($"-curve[{curveCounter - 2}]");
                        curveLoopSign = "";
                        previousStart = startpoint;
                        previousEnd = endpoint;

                    }
                    else if (areCoordinatesEqual(endpoint, previousStart) == true)
                    {
                        // remove last curve in a surface and change its sign becuase its direction is not correct
                        curveloop.RemoveAt(curveloop.Count - 1);
                        // Change its direction
                        curveloop.Add($"-curve[{curveCounter - 2}]");
                        // Change curve direction
                        curveLoopSign = "-";
                        previousStart = endpoint;
                        previousEnd = startpoint;

                    }
                    else if (areCoordinatesEqual(endpoint, previousEnd) == true)
                    {
                        // Change curve direction
                        curveLoopSign = "-";
                        previousStart = endpoint;
                        previousEnd = startpoint;

                    }
                    else
                    {
                        TaskDialog.Show("Error", "This condition is not defined!");
                    }
                }
                else // First curve in a surface
                {
                    previousStart = startpoint;
                    previousEnd = endpoint;
                }

                curveloop.Add($"{curveLoopSign}curve[{curveCounter - 1}]");

            }

            geometryStringBuilder.AppendLine("Coherence;"); // Remove all duplicate elementary entities 


            //for (int i = 0; i < curveCounter;i++)
            //{
            //    curveloop.Add($"curve[{i}]");
            //}
            geometryStringBuilder.AppendLine("//+");
            geometryStringBuilder.AppendLine("cloop = newll;");
            geometryStringBuilder.AppendLine($"Curve Loop(cloop) = {{{String.Join(", ", curveloop)}}};");


            geometryStringBuilder.AppendLine($"surface1 = news;"); //New surface
            geometryStringBuilder.AppendLine($"Surface(surface1) = {{cloop}};"); //Surface
            geometryStringBuilder.AppendLine($"Physical Surface(\"{groupName}\") += {{ surface1 }};\n");

            //geometryStringBuilder.AppendLine("//+");
            //geometryStringBuilder.AppendLine("Recombine Surface{:};"); // Quadratic
            ////stringBuilder.AppendLine("Recombine Volume{:};");
            //geometryStringBuilder.AppendLine("Transfinite Surface{:};"); // Structured
            ////stringBuilder.AppendLine("Transfinite Volume{:};");
            //geometryStringBuilder.AppendLine("Geometry.Tolerance = 1e-3;");
            ////Mesh.CharacteristicLengthMax = 0.1; // Set maximum mesh size
            ////Mesh.CharacteristicLengthMin = 0.01; // Set minimum mesh size
            ////Mesh.Algorithm = 5; // Set the meshing algorithm (e.g., Delaunay)
            ////Mesh.RecombineAll = 1; // Recombine triangles into quads
            //// Automatically generate the mesh when the file is opened
            ////Mesh 2; // This command triggers the 2D mesh generation
            //geometryStringBuilder.AppendLine("Mesh 2;");

            //geometryStringBuilder.AppendLine("Coherence Mesh;"); // Remove all duplicate mesh nodes in the current mesh.

            //try
            //{
            //    using (StreamWriter writer = new StreamWriter(Path.GetDirectoryName(uidoc.Document.PathName)+$"\\{filename}"))
            //    {
            //        writer.Write(geometryStringBuilder.ToString());
            //    }
            //}
            //finally
            //{
            //    TaskDialog.Show("R", $"The selected items exported to:\r\n{Path.GetDirectoryName(uidoc.Document.PathName)}\n\\{filename}");
            //}

            return geometryStringBuilder;

        }

        private bool areCoordinatesEqual(XYZ Point1, XYZ Point2)
        {
            if (Math.Round(Point1.X) == Math.Round(Point2.X) &&
                    Math.Round(Point1.Y) == Math.Round(Point2.Y) &&
                    Math.Round(Point1.Z) == Math.Round(Point2.Z))
            {
                return true;
            }
            else
            {
                return false;
            }
        }


    }
}
